include:
  - project: 'omniverse/devplat/gitlab/templates/common/compliance'
    file: 'modules/omniverse-repo-compliance.gitlab-ci.yml'
    ref: v1_latest

variables:
  OSEC_NSPECT_ID: NSPECT-9GUM-4H71
  OSEC_SONARQUBE_ENABLED: true
  OSEC_CHECKMARX_ENABLED: false
  OSEC_PULSE_TRUFFLEHOG_ENABLED: true
  OSEC_OMNI_PULSE_ENABLED: false

# overrides for sonarqube job to enable C/C++ analysis
osec:sonarqube:
  variables:
    SONAR_CFAMILY_COMPILE_COMMANDS: _build/linux-x86_64/release/compile_commands.json
    SONAR_EXCLUSIONS: "_build/**,_repo/**,\
      \
      source/tests/**,\
      "
    LINBUILD_EMBEDDED: "1"
  before_script:
    # Additions to enable C/C++ scan via sonar's compile_commands.json, you still need all of the
    # packman headers and generated headers in place for this analysis to work.
    # So we run repo --generate
    - ./repo.sh build --generate --config release
