[[dependency]]
python = "../_build/target-deps/python"
packages = [
    "pyzmq==25.1.2", # 26.4.0 no longer works as prebunlde.
    "protobuf==5.26.0",
]

target = "../_build/target-deps/pip_prebundle"
platforms = ["*-x86_64"]
download_only = false
append_to_install_folder = true
