# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_control_message.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cserver_control_message.proto\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"J\n\x14\x43\x61meraControlCommand\x12\x1c\n\njoints_vel\x18\x01 \x01(\x0b\x32\x08.Vector3\x12\x14\n\x0c\x66ocal_length\x18\x02 \x01(\x01\"(\n\x0fSettingsCommand\x12\x15\n\radaptive_rate\x18\x01 \x01(\x08\"D\n\rFrankaCommand\x12\x1e\n\x0c\x65\x66\x66\x65\x63tor_pos\x18\x01 \x01(\x0b\x32\x08.Vector3\x12\x13\n\x0bshow_marker\x18\x02 \x01(\x08\"\xb2\x01\n\x14ServerControlMessage\x12\x37\n\x16\x63\x61mera_control_command\x18\x01 \x01(\x0b\x32\x15.CameraControlCommandH\x00\x12,\n\x10settings_command\x18\x02 \x01(\x0b\x32\x10.SettingsCommandH\x00\x12(\n\x0e\x66ranka_command\x18\x03 \x01(\x0b\x32\x0e.FrankaCommandH\x00\x42\t\n\x07\x63ommandb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_control_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTOR3']._serialized_start=32
  _globals['_VECTOR3']._serialized_end=74
  _globals['_CAMERACONTROLCOMMAND']._serialized_start=76
  _globals['_CAMERACONTROLCOMMAND']._serialized_end=150
  _globals['_SETTINGSCOMMAND']._serialized_start=152
  _globals['_SETTINGSCOMMAND']._serialized_end=192
  _globals['_FRANKACOMMAND']._serialized_start=194
  _globals['_FRANKACOMMAND']._serialized_end=262
  _globals['_SERVERCONTROLMESSAGE']._serialized_start=265
  _globals['_SERVERCONTROLMESSAGE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
